### ISSUE TITLE
Yeoman not recognizing generator when phaser installed with Bower?

### ISSUE THREAD

**Issue by m3hr** [julien/generator-phaser#18]
I installed phaser with bower and have it in my bower.json, but after installing generator-phaser running a `yo phaser` gives

```You don't seem to have a generator with the name phaser installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].```

when it also accepts generator-phaser as installed. I'm confused. Am I missing something basic?

**Comment by julien** [comment]
Hi,

Did you install generataor-phaser or just phaser?

**Comment by m3hr** [comment]
I installed both, But I got phaser from Bower. Does it have to be from npm?

**Comment by m3hr** [comment]
Hmmm, seems like this isn't specific to this program. Sorry to bother!

**Comment by m3hr** [comment]
https://github.com/yeoman/yo/issues/264 This was the issue.

**Comment by julien** [comment]
Thanks

**Comment by julien** [comment]
:beer:
