### ISSUE TITLE
Preload tilemap

### ISSUE THREAD

**Issue by MRdotB** [julien/generator-phaser#19]
Hi,
I have an issue, when i try to preload a json tilemap.
this.load.tilemap('level1', 'assets/level1.json', null, Phaser.Tilemap.TILED_JSON);
I get "Phaser' is not defined" in my terminal.
How can I load the tilemap properly?

**Comment by GlennGeenen** [comment]
Your game runs without a tilemap? It's correct how you load the tilemap.

Phaser is not defined look like your game can't find Phaser what means that bower didn't install phaser. You can do 'bower install' in the game directory to get phaser.
