### ISSUE TITLE
Keep phaser separate in build.

### ISSUE THREAD

**Issue by GlennGeenen** [julien/generator-phaser#22]
Currently the build process packages all javascript together in main.min.js. I wonder if it wouldn't be better to keep phaser and your game separate. Many times you want to link phaser to a cdn or the same file so it can be cached.

Any reason these are together (apart of having a http request less)?

**Comment by julien** [comment]
The reason for this was just a personal preference.

In bigger projects I also tend to minify "vendor" code separately from "project" code, so I don't mind if this gets changed.
