### ISSUE TITLE
Is it possible to generate a blank application?

### ISSUE THREAD

**Issue by thesabbir** [julien/generator-phaser#27]
Every time I generate I need to refactor to get it going. EG remove example codes & assets. Is it possible to generate a blank application?

**Comment by julien** [comment]
At the moment no, but we can add that option.

**Comment by thesabbir** [comment]
@julien  that would be very helpful and a must have option. If you give me some direction may be I can help :+1:

**Comment by GlennGeenen** [comment]
:+1:  I think an empty project is a better default option than what we have now. I'll look into it this weekend if you haven't started yet.

**Comment by julien** [comment]
@GlennGeenen Thanks for the feedback,

I actually find myself doing the same as @thesabbir each time too.

We can provide the base "scaffold" without the assets. 

What would you include and what wouldn't you in the project?

I started working on a separate branch [here](https://github.com/julien/generator-phaser/tree/issue-27), what do you think?

**Comment by GlennGeenen** [comment]
I was thinking to only keep the preloader for assets.
Menu still listens to input (so you can start the game), replace drawing bitmapfont with drawing Arial.

        var text = this.add.text(this.game.width * 0.5, this.game.height * 0.5, 'Hello World', {
            font: '42px Arial',
            fill: '#ffffff',
            align: 'center'
        });
        text.anchor.set(0.5);

Game with empty create and update methods (remove onInputDown).

**Comment by julien** [comment]
Cool,
I'll make the change as soon as I can, I'm quite busy right now. Would you be ok to review the pull request once the changes are made?

**Comment by julien** [comment]
Ok made some changes
