### ISSUE TITLE
State question

### ISSUE THREAD

**Issue by LunarDevelopment** [julien/generator-phaser#29]
Hello, 

I know that this is a wider question about phaser but, its one I cant find a decent answer to anywhere I look. 

Basically: Should I create a state for every level of a game? 

If so then that would imply I'll be best off creating a module for each character and for the game mechanics.

As a side note I'm starting a long term project to make a game similar to final fantasy tactics advance or tactics ogre etc. (grid based, turn based strategy)

Any advice beyond my initial question is also amazingly appreciated.

Lewis

**Comment by GlennGeenen** [comment]
You create prototypes in the same way as you would create classes in other programming languages. You should do this for player, enemy, weapon, level, ... You don't want to repeat yourself so all common logic should go in prototypes.

It is not necessary to create a new state for every level, you could also create a level prototype and just load the level you need in your game state.

Phaser can handle grid based games really well, check out http://www.mapeditor.org, you could use it as map editor.

**Comment by aido179** [comment]
Depends entirely on the style of level you will have. I would personally create a state for each functionally separate "screen" of your game, but that is entirely up to you.

This issue should be closed.
