### ISSUE TITLE
yo phaser:state doesn't work

### ISSUE THREAD

**Issue by erbridge** [julien/generator-phaser#30]
Running `yo phaser:state` runs the app generator again.

**Comment by julien** [comment]
@erbridge thanks I'll check it out

**Comment by garbados** [comment]
I think I've found the issue. The version of the generator on NPM doesn't include the `yo phaser:state` sub-generator. Uploading the latest version of the code to NPM should fix the problem for users like @erbridge.

**Comment by julien** [comment]
Hi @erbridge could you check out 0.31.0 - should solve your issue

Thanks

**Comment by vbarinov** [comment]
I have generator-phaser@0.31.0 and subgenerator doesn't work

**Comment by producerism** [comment]
I have generator-phaser@0.33.0, and when running "yo phaser:state" I get the following message:

> You don't seem to have a generator with the name phaser:state installed.

**Comment by julien** [comment]
Sorry for not replying earlier, will check it out
