### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by tvalentius** [julien/generator-phaser#32]
Hi there,

thanks for creating the generator for phaser.

But unfortunately when i tried to run "npm start" command, it throws an errors
<pre> <code>
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cobageneratorphaser@0.0.0 start: `node ./node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cobageneratorphaser@0.0.0 start script 'node ./node_modules/gulp/bin/gulp.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cobageneratorphaser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/gulp/bin/gulp.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cobageneratorphaser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cobageneratorphaser
npm ERR! There is likely additional logging output above.
</code></pre>

**Comment by GlennGeenen** [comment]
I just tested on node 4 and everything works as expected.

The generator uses the latest versions for devDependencies, this means breaking changes could popup. It's probably safer to fix them on major versions. Either way the current version seems to work so if you update everything should be fine (npm install -g yo generator-phaser).

**Comment by julien** [comment]
Hey @tvalentius, are you sure about this?

In the error message you posted it sees that the problem doesn't come from the generator-phaser module

``` Failed at the cobageneratorphaser@0.0.0 ````

I've got an update on the way which will likely use browserify get rid of bower and while I'm at it, I'll probably do what @GlennGeenen  said about the devDependencies (thanks for the heads up) ;)

Cheers
