### ISSUE TITLE
LiveReload doesn't trigger

### ISSUE THREAD

**Issue by mokargas** [julien/generator-phaser#36]
Hey there

I've created a new phaser project via the generator, and I'm running the embedded budo server via npm start, as recommended. Making changes to main.js (or indeed any other JS file) doesn't trigger livereloading, despite --live being set in the package.json scripts entry. The livereload js file is being injected successfully, but bundle.js is never regenerated without killing the server and reloading

Please advise if further information is required.

Mac OSX 10.10.5
Chrome  51.0.2704.103

**Comment by julien** [comment]
Hey @mokargas, I'll have a look at this ASAP. I develop mainly on Linux but I can have a look on Mac. Thanks for reporting!

**Comment by mokargas** [comment]
No worries Julien

I've just tested on my Windows 7 machine and everything works as expected.

**Comment by mokargas** [comment]
No, unfortunately this needs to run on a Mac, I'll keep investigating

**Comment by julien** [comment]
No worries, I'll try having a look on OS X too see if I can find something

**Comment by julien** [comment]
Hey again 

Just a thought, 
Did you check with several browsers (and in "private" mode)?
Did you try tools like tail and curl?
I know this might seem stupid but when you modify one of the .js files, do you  see messages in your terminal concerning browserify?

**Comment by julien** [comment]
Tested on OSX El Capitan with NodeJS v6.3.1.
Closing for now.
