### ISSUE TITLE
'npm run build' failed right out of the box.

### ISSUE THREAD

**Issue by smatthews1999** [julien/generator-phaser#40]
This is not working on a newly created project... 
In fact it's creating a directory in my root called '-p'.
[npm-debug.log.txt](https://github.com/julien/generator-phaser/files/428299/npm-debug.log.txt)

**Comment by julien** [comment]
hi @smatthews1999, 

Thanks for reporting.
so according to the log, this is what's failing

```shell
21 error Failed at the yotest@1.0.0 prebuild script 'mkdir -p build && mkdir -p build/custom '.
```

I'll check it out, but I can't test on Windows right now.

**Comment by smatthews1999** [comment]
In fact it's creating a directory in my root called '-p'.
Can you please tell me where this script is located?  I am not familiar with this build system.

**Comment by julien** [comment]
oops.

Well yeah sure, check out the `scripts` section of the `package.json` file, if it's not urgent I'm working on a fix that should be up in the next 30 minutes.

**Comment by julien** [comment]
@smatthews1999  I just pushed the `fix_mkdir` branch which should solve the problem, I tested on linux and I still works, I'll have time to try on Windows later on but in the meantime you can try it out.

**Comment by julien** [comment]
@smatthews1999 I just published v0.41.0 on npm tell me how that works for you. Cheers

**Comment by smatthews1999** [comment]
I found the commands in package.json and was trying some fixes.

but your fix works great!

Thanks.

**Comment by julien** [comment]
Good news ;) and you're welcome.
