### ISSUE TITLE
README.md has incorrect info about creating directory.

### ISSUE THREAD

**Issue by AMadHammer** [julien/generator-phaser#48]
> Create a new directory for your game:
> 
> Unix/OSX : mkdir ~/Desktop/mygame && cd $_
> Windows : mkdir %USERPROFILE%\Desktop\mygame && cd %USERPROFILE%\Desktop\mygame

The OSs are reversed. I used the top one to create the directory on my Windows machine

**Comment by julien** [comment]
They aren't.
Did you use PowerShell?

**Comment by AMadHammer** [comment]
I used git bash. I can see the confusion though so it is all fine.
