### ISSUE TITLE
Prefab Inclusion

### ISSUE THREAD

**Issue by B3L7** [julien/generator-phaser#51]
It's stated that generated states are included in main.js but I see nothing about prefabs. When I try and call a generated prefab it errors as undefined. Do I  need to include my prefabs manually and if so what is the best way so that they will end up in the final build. Thanks!

**Comment by julien** [comment]
Hey @B3L7,

Did you try running

```shell
yo phaser:prefab
```

You should see something like this

```shell
$ yo phaser:prefab
Creating a new Phaser Prefab.
? What type of prefab would you like to create? (Use arrow keys)
❯ prefabSprite 
  prefabGroup 
  prefabTileSprite 
  prefabEmitter 
  prefabText
```

**Comment by B3L7** [comment]
Got it. Took a look at your example game and found I had to import the prefab directly into the state. Thanks for the great work!

**Comment by julien** [comment]
Thanks
