### ISSUE TITLE
Deploying to heroku?

### ISSUE THREAD

**Issue by AMadHammer** [julien/generator-phaser#52]
Not sure if this qualifies as an issue, but did anyone successfully deploy this project to heroku? I am following the tutorials and I am sure that the issue that I run into is at creating the procfile where heroku does not understand the npm start because it does not have budo installed. 

I also tried running the project with node main.js with no luck as I can't find info on how phaser code works.

If anyone can direct me to the right location then I will appreciate it.

**Comment by julien** [comment]
Hi @AMadHammer,

It's not an issue for now, since deploying to heroku is not implemented.

But you could probably run the build on heroku, [this article](https://www.sitepoint.com/deploying-heroku-using-gulp-node-git/) might help.
