### ISSUE TITLE
es2015 error

### ISSUE THREAD

**Issue by tskorupka** [julien/generator-phaser#53]
Opening terminal. Creating new directory with following command and moving into new directory:
`mkdir -p Games/lucky && cd Games/lucky`

Running following command: [Updating npm, yo and installing generator-phaser]
`npm install npm -g && npm install yo generator-phaser -g && yo`

Now running generator and picking up options such as:
`? What's the name of your application lucky`
`? Which version of Phaser do you want? Arcade Physics + P2 Physics (Default)`
`? Which ECMAScript version do you want to use? ECMAScript 6/2015 (Default)`
`? Output an example game or boilerplate code? Boilerplate`

Installed properly, running command:
`npm start`

Result given:

> ➜  lucky npm start
> lucky@1.0.0 start /Users/ts/Games/lucky
> budo src/main.js:bundle.js --live -- -d -e src/main.js -t [babelify --comments false --presets es2015]
> [0000] info  Server running at http://192.168.0.5:9966/ (connect)
> [0000] info  LiveReload running on 35729
> Error: Couldn't find preset "es2015" relative to directory "/Users/ts" while parsing file: /Users/ts/Games/lucky/src/main.js

**Comment by julien** [comment]
@tskorupka thanks for reporting the error

Some dev dependencies are probably out of date. I'll going to do some clean up and fix.

**Comment by julien** [comment]
@tskorupka could you please tell me which OS you'e using? I've just tested on Linux and Mac OS with no issue. Thanks

**Comment by tskorupka** [comment]
@julien here you have.

Tried to do so on

* MacOS 10.12.3 with (LTS) `node v6.4.0` and `npm v4.2.0`

Directory for babel-preset-2015 exist under
* `/Users/ts/Games/lucky/node_modules/babel-preset-es2015`

Thanks

**Comment by tskorupka** [comment]
@julien Updated node and npm in following steps

Used brew to unlink old version by
`brew unlink node`

Next step was to download latest LTS version of node v6
`brew install node@6`

Recreated new project from generator with
`node v6.9.5` and `npm v3.10.10`

Same error occurs.

**Comment by julien** [comment]
@tskorupka sorry to hear that, could you attach the `npm-debug.log` if you happen to have it, I'm trying to reproduce the issue but still no luck. Thanks

**Comment by tskorupka** [comment]
I do not have `npm-debug.log` but I could manage to try run build script from `package.json` located in project and there is log

```
➜  lucky npm run build

> lucky@1.0.0 prebuild /Users/ts/Games/lucky
> mkdirp build


> lucky@1.0.0 build /Users/ts/Games/lucky
> npm run build:js && npm run build:css && npm run build:html && npm run copy:all


> lucky@1.0.0 build:js /Users/ts/Games/lucky
> browserify -d -e src/main.js -t [babelify --comments false --presets es2015] | uglifyjs -cm > build/bundle.min.js

Error: Couldn't find preset "es2015" relative to directory "/Users/ts" while parsing file: /Users/ts/Games/lucky/src/main.js
    at /Users/ts/Games/lucky/node_modules/babel-core/lib/transformation/file/options/option-manager.js:292:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/ts/Games/lucky/node_modules/babel-core/lib/transformation/file/options/option-manager.js:274:20)
    at OptionManager.mergePresets (/Users/ts/Games/lucky/node_modules/babel-core/lib/transformation/file/options/option-manager.js:263:10)
    at OptionManager.mergeOptions (/Users/ts/Games/lucky/node_modules/babel-core/lib/transformation/file/options/option-manager.js:248:14)
    at OptionManager.init (/Users/ts/Games/lucky/node_modules/babel-core/lib/transformation/file/options/option-manager.js:367:12)
    at File.initOptions (/Users/ts/Games/lucky/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/ts/Games/lucky/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/ts/Games/lucky/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (/Users/ts/Games/lucky/node_modules/babelify/index.js:27:24)

> lucky@1.0.0 build:css /Users/ts/Games/lucky
> cleancss css/main.css -o build/main.min.css


> lucky@1.0.0 build:html /Users/ts/Games/lucky
> htmlprocessor index.html -o build/index.html

File "build/index.html" created.

> lucky@1.0.0 copy:all /Users/ts/Games/lucky
> npm run copy:assets && npm run copy:phaser


> lucky@1.0.0 copy:assets /Users/ts/Games/lucky
> ncp assets build/


> lucky@1.0.0 copy:phaser /Users/ts/Games/lucky
> ncp node_modules/phaser/build/phaser.min.js build/phaser.min.js
```

**Comment by julien** [comment]
@tskorupka thanks for the information. 

In this error log on this line

```
Couldn't find preset "es2015" relative to directory "/Users/ts" while parsing file: /Users/ts/Games/lucky/src/main.js
    at /Users/ts/Games/lucky/node_modules/babel-core/lib/transformation/file/options/option-manager.js:292:19
    at Array.map
```

Is seems that the `npm run build` command is being executed from the `/Users/ts` directory and not `/Users/ts/Games/lucky/` but appart from that I can't really help much, but will keep on investigating.

**Comment by tskorupka** [comment]
@julien some guide on stackoverflow helped me.

I had to create `.babelrc` file with such content:
```
{ "presets": [ "es2015", "react" ] }
```

I belive that it should have defined local babel presets for project.

This fixed issue for me.

>[StackOverflow](http://stackoverflow.com/questions/40188578/webpack-babel-couldnt-find-preset-es2015-relative-to-directory)

**Comment by julien** [comment]
@tskorupka I'm glad that fixed it.

However, as you can see [here](https://github.com/julien/generator-phaser/blob/master/app/templates/es6/_package.json#L6-L14), the build scripts do use the `--preset` option

```
"start":  "budo src/main.js:bundle.js --live -- -d -e src/main.js -t [babelify --comments false --presets es2015]",
 ...
"build:js": "browserify -d -e src/main.js -t [babelify --comments false --presets es2015] | uglifyjs -cm 
```

so there should be no need for a `.babelrc` file.  Can I ask you in which directory you created it?

Also `react` is not used so it shouldn't be required in the presets, have you tried removing it?

Thanks

**Comment by tskorupka** [comment]
@julien Sorry for not responding.

I've created `.babelrc` file in main directory of project.
Didn't tried to remove `react`.

Greets

**Comment by julien** [comment]
@tskorupka no worries and thanks for the feedback.
