### ISSUE TITLE
Asset folder building problem

### ISSUE THREAD

**Issue by henriquelalves** [julien/generator-phaser#54]
npm: 4.0.5v; LinuxMint 17.2 Cinnamon.

I just installed this generator, and something I was troubled at is that "npm run build" command won't work properly if you don't create a subfolder also named "assets" inside you "assets" folder to put your files there; otherwise what will happen is that all your asset files will be "built" on the root folder of the project, and Phaser won't find them when loading.

This also happens with the generator game example, which means you can't test it from scratch just by generating and building it.

**Comment by henriquelalves** [comment]
I'm a total newbie at npm, but the problem is easily solvable by changing line 13 at "package.json" from
`"copy:assets": "ncp assets build/",`
to
`"copy:assets": "ncp assets build/assets/",`

I'm not sure if this is the best solution or I was just mistaken somewhere during the npm built, though.

**Comment by julien** [comment]
Hi  @henriquelalves,

Thanks for reporting this issue and providing the solution, and sorry for the late reply.
